version: "3.9"
services:
  worker:
    build: .
    environment:
      SESSION: $SESSION
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None 
      BOT_TOKEN: $BOT_TOKEN # Not mandatory
      COMMAND_HAND_LER: $COMMAND_HAND_LER # mandatory
      TZ: $TZ #mandatory
      UPSTREAM_REPO: $UPSTREAM_REPO #mandatory
      ALIVE_NAME: $ALIVE_NAME #mandatory
      OKTETO_TOKEN: $OKTETO_TOKEN











