services:
  - type: web
    plan: free
    name: War
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & bash warbot
    repo: https://github.com/TECHNOBOT-OP/warbot   
    branch: master
    envVars:
      - key: ABUSE
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ENV
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: DATABASE_URL
        sync: false
      - PYTHON_VERSION
        sync: false
    autoDeploy: false
